# Generated by Django 5.0.4 on 2024-04-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_page'),
    ]

    operations = [
    ]
